### ISSUE TITLE
feature request: one to many broadcast

### ISSUE THREAD

**Issue by eisneim** [rtc-io/rtc#16]
we wanted build a classroom app which only teacher can speak and student can only listen, is there a way to take advantage of webRTC and rtc.io to achieve this? 

the only solution i can think of is:   make nodejs server and teacher as Peer, and nodeJS server send video stream to students via websocket, which is not really P2P

**Comment by DamonOehlman** [comment]
It's definitely doable, but broadcast is not WebRTC's strong suit at the moment.  How many students do you want a teacher to be able to broadcast to?

**Comment by eisneim** [comment]
20-50 would it be possilble? this might require the "teacher " have a super fast bandwidth if without a CMU

**Comment by eisneim** [comment]
i've spent 2 day trying to choose the "correct" method to achieve, and i found this: http://stackoverflow.com/questions/18318983/webrtc-scalable-live-stream-broadcasting-multicasting
maybe i should give janus a try

**Comment by DamonOehlman** [comment]
I would definitely recommend having a look at Janus as it's fairly easy to get running, and it is awesome :)

**Comment by eisneim** [comment]
thanks a lot
