### ISSUE TITLE
live Video streaming

### ISSUE THREAD

**Issue by muralidhar-challa** [rtc-io/rtc#22]
I want to create a room based live video streaming website with integrated chat. Are there any modules in rtc.io that could help my purpose.

**Comment by silviapfeiffer** [comment]
Hi @srmurali002 - you can use the code at https://github.com/rtc-io/demo-quickconnect to create a rtc.io based video conferencing example. You have to set it all up yourself though, including the signalling server, because the demo signalling server that we used to use is currently down.

**Comment by muralidhar-challa** [comment]
But many of your examples are using a modified rtc.js file.Where can I find a full version of rtc.js.

**Comment by silviapfeiffer** [comment]
It's all in the npm packages with source code in this group's repositories.
