### ISSUE TITLE
rtc.local is undefined

### ISSUE THREAD

**Issue by bugwheels94** [rtc-io/rtc#25]
When I am implementing

http://rtc.io/tutorial-rtc-video-chat.html with my own local singanalling server as https://switchboard.rtc.io is probably down. I am getting error 

TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

When doing ```localVideo.appendChild(rtc.local);```

And also I am not able to call the init method on rtc

**Comment by silviapfeiffer** [comment]
Did you create your own rtc.js ? I don't think we've published a new version recently, so you'll need to build it from scratch.

**Comment by bugwheels94** [comment]
No. I didn't. I used the file frome [here](https://github.com/rtc-io/rtc/blob/master/dist/rtc.min.js). If I build the file myself, will the tutorial still work? Or the tutorial is also outdated?

**Comment by besserwisser** [comment]
Hey, I have the same issue. Used the npm package. What was you solution?

**Comment by bugwheels94** [comment]
@besserwisser I never used this repo. This is a dead project AFAIK. I was looking at heavy video calls so went with kurento media server and their front end library and kurento was not a stable software so moved to janus media server with kurento frontend library.
